spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Hongkong&useUnicode=true&characterEncoding=UTF-8
    password: claacgs
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    # 下面为连接池的补充设置，应用到上面所有数据源中
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
  # redis 配置
  redis:
    # Redis数据库索引(默认为0)
    database: 1
    # Redis服务器地址
    host: 47.105.154.233
    # 端口
    port: 6379
    # 连接密码(默认为空)
    password: 123456
    jedis:
      pool:
        # 连接池最大连接数(使用负值表示没有限制)
        max-active: 200
        # 连接池最大阻塞等待时间(使用负值表示没有限制)
        max-wait: -1
        # 连接池总的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间(毫秒)
    timeout: 1000
  # rabbitmq 配置
  rabbitmq:
    host: 47.105.154.233
    port: 5672
    username: guest
    password: guest
  # JPA 配置
  jpa:
    hibernate:
      # 更新或者创建表结构
      ddl-auto: update
    # 控制台显示SQL
    show-sql: true
  # Jest 配置
  elasticsearch:
    rest:
      uris: ["http://47.105.154.233:9200"]
    jest:
      uris: ["http://47.105.154.233:9200"]

  # SpringData ElasticSearch 配置
  data:
    elasticsearch:
      cluster-nodes: 47.105.154.233:9300
      cluster-name: docker-cluster
      repositories: true
# mybatis 配置
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: # 若下列映射文件与Mapper.java接口文件在同一个包中，则次字段无需配置
    - classpath:mybatis/mapper/*.xml
    - classpath:com/**/mapper/*.xml

# 设置打印查询语句
logging:
  level:
    com:
      garen:
        community:
          mapper: debug

# rabbitmq 自定义配置
rabbit:
  custom:
    exchangeName: test.amqpexchange
    queueName: test.amqpqueue
    routingName: test.amqprouting

#### redis topic ######
demo:
  topic: redis/pubsub


# 监控
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  server:
    servlet:
      context-path: /manage
    port: 8181

